name: AWS S3 Uploading

on:
    workflow_dispatch:
      inputs:
        environment:
          description: The target AWS account
          type: choice
          required: true
          default: 'nonprod'
          options:
            - nonprod
            - prod


    
jobs:
    deploy:
      runs-on: ubuntu-latest
      environment: ${{ inputs.environment }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Setup Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.12'
        
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        
        - name: Collecting data
          run: |
            echo "Collecting data..."
            chmod +x ./deploy.sh
            ./deploy.sh img $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY $AWS_SESSION_TOKEN $AWS_DEFAULT_REGION

